language: java
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

sudo: required

before_install:
  - mysql -e 'CREATE DATABASE ponto_inteligente;'
